# Generated by Django 5.2.8 on 2025-11-19 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Foto de perfil (JPG, JPEG ou PNG, máx 2MB)",
                null=True,
                upload_to="profile_pictures/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"],
                        message="Apenas arquivos JPG, JPEG ou PNG são permitidos.",
                    )
                ],
            ),
        ),
    ]
